spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 965628037149-ee3ta8tuo6hs8vflas6nqpnqosqjsml2.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            client-name: Google
          naver:
            client-id: UI7mivmVujEvYkaRGIPH
            client-secret: UFe3LVpRkR
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
          kakao:
            client-id: 0d624716f3d8101363ece56d98954baf
            client-secret: rJC7J2IOWRDlJkLO6nLwCTD0xHRemgWH
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, profile_image
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id